"""Add Customer, Loan, GoldItem, and Payment models

Revision ID: 27ba18e44152
Revises: 5e0b2b9b486c
Create Date: 2025-09-05 07:00:27.668975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba18e44152'
down_revision = '5e0b2b9b486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('kyc_type', sa.String(length=50), nullable=True),
    sa.Column('kyc_id_number', sa.String(length=50), nullable=True),
    sa.Column('id_proof_path', sa.String(length=255), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kyc_id_number'),
    sa.UniqueConstraint('primary_phone')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate_yearly', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interest_calculation_type', sa.Enum('DAILY', 'MONTHLY', 'YEARLY', name='interestcalculationtype'), nullable=False),
    sa.Column('payment_scheme', sa.Enum('EMI', 'BULLET', 'INTEREST_ONLY', name='paymentscheme'), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loan_start_date', sa.Date(), nullable=False),
    sa.Column('loan_duration_days', sa.Integer(), nullable=False),
    sa.Column('actual_closure_date', sa.Date(), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('next_emi_date', sa.Date(), nullable=True),
    sa.Column('loan_status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'CLOSED', 'OVERDUE', 'DEFAULTED', 'AUCTIONED', name='loanstatus'), nullable=False),
    sa.Column('allows_early_closure', sa.Boolean(), nullable=True),
    sa.Column('allows_extension', sa.Boolean(), nullable=True),
    sa.Column('accumulated_interest', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_interest_calculation_date', sa.Date(), nullable=True),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penalty_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_loan_number'), ['loan_number'], unique=True)

    op.create_table('gold_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('gross_weight_grams', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stone_weight_grams', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('net_weight_grams', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('purity_karat', sa.Integer(), nullable=False),
    sa.Column('market_rate_per_gram', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('appraised_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stone_deduction_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('EMI', 'PARTIAL_INTEREST', 'PARTIAL_PRINCIPAL', 'FULL_CLOSURE', 'AUCTION_PROCEEDS', name='paymenttype'), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'BANK_TRANSFER', 'UPI', 'CHEQUE', 'CARD', name='paymentmode'), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_component', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_component', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_receipt_number'))

    op.drop_table('payments')
    op.drop_table('gold_items')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_loan_number'))

    op.drop_table('loans')
    op.drop_table('customers')
    # ### end Alembic commands ###
